### ISSUE TITLE
Modal CSS glitches on Mobile

### ISSUE THREAD

**Issue by AnTheMaker** [troyhunt/Coinhive#4]
There a a few CSS glitches when viewing the Modal on a mobile device, namely two:
1. The "×" button is too far on the right and partly off-screen and possibly hard to click (on a small display, e.g. smartphone)
2. When scrolling down, while the Modal is open, the background "dim" isn't continuing. Maybe this is intentional, but I don't think so.

I attached two screenshots with the two bugs.

Apart from that, great project & awesome blog post!
![Screenshot_20210401-001022_Samsung Internet](https://user-images.githubusercontent.com/18481195/113218072-30133880-927f-11eb-8e20-5594708762c1.jpg)
![Screenshot_20210401-001034_Samsung Internet](https://user-images.githubusercontent.com/18481195/113218074-31446580-927f-11eb-93d6-9b5ccff9c1a2.jpg)

**Comment by VerifiedJoseph** [comment]
Two minor changes to the modal CSS would fix these issues:
Changing the value of  `position` for `.js-modal` to `fixed` will make the modal follow the user when they scroll.
Changing the value of `right` for `.js_modal_close` to `0px` will stop the close button being cut off on small screens.

**Comment by troyhunt** [comment]
Happy to take a pull request on this 🙂

**Comment by troyhunt** [comment]
Now fixed by @VerifiedJoseph and deployed.
